### PR TITLE
A few minor improvements.

### PR DESCRIPTION
**Pull request by bemosior**
Hello! I wanted to get started working with NarraFirma, so I'm offering up a few changes I made while attempting to get oriented with the project. The contents of this PR are as follows:
# `package.json` Improvements

These changes revolve around `package.json` and its potential use.
1. Add a repository field corresponding to this git repository.
2. Add a license field corresponding to the "GPL v2 or any later version" remark in the README.
3. Adjust spacing and layout to match npm specifications.
4. Introduce `tsc` as a dependency at the top level of the project.
5. With the deprecation of `tsc`, instead use the recommended replacement package, `ntypescript`.
6. Remove the checked-in top-level node_modules directory, add it to the ignored git files, and move the `requirejs` dependency to `package.json`.

Switching from a checked-in `node_modules` to delegation to `npm` dependency installation is motivated by a movement to more standard practices, though there's a pretty heated argument in the industry about the tradeoffs of depending on the public internet.
# Introduction of Grunt

Grunt is a task-runner for node.js and serves a similar role as `make` might in other projects. It provides the ability to define tasks and chain them together, lessening the repetitious nature of some development processes. Instead of a Makefile, a Gruntfile is used.
1. Create a `tsc` task, which performs TypeScript compilation (callable via `grunt tsc`).
2. Create a `serve` task, which launches the NarraFirma node.js server (callable via `grunt serve`).
3. Set the default task to chain the `tsc` and `serve` tasks (callable via `grunt`).

The introduction of Grunt lays the groundwork for additional functionality. For example, we can easily write a Grunt task that watches for changes in `webapp/source`, automatically recompiles the TypeScript, and automatically relaunches the server.
# Summary

The major changes introduced here include the use of `ntypescript` instead of `tsc` (due to its deprecation), the delegation of top-level project dependency management to `npm`, and the introduction of Grunt for task automation.

For a new developer attempting to work with the node.js portion of the project, "getting started" is reduced to the following:
1. `npm install`
2. Use the admin utility to set the superuser credentials.
3. `grunt` (or, if it is not globally installed, `node_modules/grunt/bin/grunt`).

### CODE REVIEW

**Comment by bemosior** [comment]
Many of these changes may be presumptuous. Feel free to reject any or all of them. I intend to use NarraFirma in professional contexts, so I would like to contribute back as much as I can.

**Comment by pdfernhout** [comment]
@bemosior Thanks, Benjamin. I appreciate the effort in making improvements to NarraFirma. Thanks also for taking the time to explain the reasoning behind these changes. So far, we like about half of the commits in this pull request. :-) The others conflict with conscious design choices we have made about npm, which admittedly not everyone agrees with. Essentially, we made a conscious choice to use npm at development time and not install or build time, while also consciously choosing to rely on npm for build support instead of other tools like Grunt. Probably we should document that choice somewhere. Sorry to have wasted some of your time by not doing that sooner. Below I explain more details about the parts we like and don't like, and suggest ways for proceeding to integrate some of these changes depending on what you'd like to do.

=== More details

We'd like to upgrade package.json along **some** of the lines you outline which are thigns anyone could agree are improvements, like adding the license clause and such as we know that file is not completely filled in (including with dependencies). Thanks for pointing out tsc has been deprecated. We'd probably want to replace it with just the official "typescript" until I understand the benefits of "ntypescript" better as they apply to NarraFirma.

That said, we made the choice to check in node_modules to avoid issue like the recent ones npm users have experienced with SSL certificates and also left-pad so we don't want to exclude them from git. As you say, there is a pretty heated argument in the industry about this, and the original npm vision was to include source for specific versions of libraries in each repository. See for examples of recent problems people have had when using npm as part of the build process
http://www.letscodejavascript.com/v3/blog/2014/03/the_npm_debacle
https://news.ycombinator.com/item?id=11348798

Also, as we've already imported the source into the repo, it won't save people much time or space cloning the repo to exclude the node_modules source now.

Many people adopt the approach you outline using a separate task runner as with the popularity of Grunt. But, we made the conscious choice to avoid Grunt, Gulp, Broccoli and other similar task runners as just an extra unneeded dependency at this point and to push npm as far as we could first instead. See for example how to do a build process with npm:
http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/
http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/

The npm build process is still rougher than it has to be though. For example, we should ideally break up the long npm run task for building the WordPress module into subtasks rather than have one long line.

You can monitor TypeScript changes and even relaunch the app from npm without Grunt or similar. So, we don't see that as a compelling argument for picking a task runner. Here is one example of what could (and no doubt should) be added to the package.json npm run scripts for development support:

```
"tsc:w": "tsc -w",
```

The Angular TypeScript quickstart has an example of doing this along with also using "concurrently" to run both a server and the tsc watch process, which we'd like to see adapted for NarraFirma and Node.js (you may have to pick "TypeScript from the dropdown to see the exact example for TypeScript instead of just JavaScript):
https://angular.io/docs/ts/latest/quickstart.html

While we like several improvements you made, because this pull request also adds some extra dependencies which will make the application somewhat harder to install and maintain due to increasing the complexity of the build process, for what does not yet seem to us to add significant value for the extra complexity, we don't want to integrate the pull request it as-is in its entirety, sorry.

So, depending on what you have time and/or inclination to do, there are a couple of ways forward. 
- You could update the pull request to have just those minimal changes mentioned above (with or without extra npm build features) and we could accept it in its entirety then. 
- Or, you could perhaps split this pull request up into a few separate pull requests, taking the other changes for Grunt and excluding the npm packages and making them into other pull requests and we could just accept the pulls we like, and I could close this larger one. I still doubt we would integrate the Grunt or npm pulls right now -- but other people might like those pull requests for their own repos, and maybe we'll come around eventually to see the benefits of those changes. 
- Or, we could look into cherry-picking the commits we like now from this pull request, making some additional changes mentioned above like to add "tsc -w" and "concurrently" for use with npm run if you don't have time/inclination right now to make such changes.

Please let me know how you would like to proceed based on the above feedback. Again, thanks for your involvement in making NarraFirma better and more useable for more people.

**Comment by bemosior** [comment]
This is excellent feedback; thank you! I am happy to engage with your existing design philosophy.

I intend to use this PR issue to direct each sub-topic to its own issue or PR, as appropriate. I hope to have time tomorrow.

**Comment by bemosior** [comment]
Keeping track below of what I intend to do:
- [x] New pull request 'A': Repository field npm warning remediated.
- [x] New pull request 'A': License field npm warning remediated.
- [x] New pull request 'A': Layout and spacing formatted per npm specifications.
- [x] New issue 'B': tsc dependency explicitly defined.
- [x] Discard: npm-installed modules now git-ignored.
- [x] Discard: Checked-in dependencies removed.
- [x] New issue 'B': requirejs dependency explicitly added.
- [x] New issue 'C': tsc deprecated, replaced by ntypescript. (#16)
- [x] Discard: Grunt (make-like utility) integrated, tsc task added as default.
- [x] Discard: Default grunt task (tsc/serve) implemented.
- [x] Discard: Gruntfile.js indentation converted to spaces.
- [x] Discard: requirejs downgraded to match originally checked-in files.
- [x] Discard: tsc task made directly-callable.
- [x] Discard: serve task made directly-callable.

**Comment by bemosior** [comment]
I regrettably used `master` in the fork when creating this PR, which is no good (chalking it up to inexperience with PRs). I do want to keep the fork's master up to date easily while not polluting future PRs with undesired commits. As a result, I am unfortunately going to rewrite history with forced push on the fork. This may mess up the coherence of this PR, but the description and comments may be useful enough.

**Comment by pdfernhout** [comment]
@bemosior Thanks for your work on this. I have merged the other two pull requests

Force pushes are quite OK in pull requests to improve them, but I am sorry to see all the commits gone as they were useful references as to node module dependencies as I think about the points you raise in #17. We will likely work through that in a somewhat different way, but if you still happen to have an old copy of the final package.json from all the commits in this issue, it might be worth pasting it in as a comment for future reference.

**Comment by bemosior** [comment]
I've opened (and subsequently closed) a new PR (#20) so the original changes can be easily referenced.

**Comment by pdfernhout** [comment]
@bemosior Thanks for creating that reference.

**Pull request closed without merging**
